
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NextThemeProvider from "@/Providers/NextThemeProvider";
import Navbar from "@/Component/Navbar";
import Footer from "@/Component/Footer";
import { ToastContainer } from "react-toastify";

const Plus_Jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${Plus_Jakarta.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className=" bg-background text-foreground min-h-full flex flex-col">
      <NextThemeProvider>
        <Navbar></Navbar>
          <main>{children}</main>
          <Footer></Footer>
           <ToastContainer />
      </NextThemeProvider>
      </body>
    </html>
  );
}
